### ISSUE TITLE
Improvement : Close color panel on 🎨 button click

### ISSUE THREAD

**Issue by alpliar** [Tsuricate/YAAC_front#3]
Hi @Tsuricate ! Nice work, thanks for sharing ! 👏

As a user done choosing hair color, I expect color panel to be closed when clicking on palette 🎨 button (same behaviour as ◀️ BACK button is expected).

Steps to reproduce :
* Choose a colorable category (ex : hair)
* Click on palette 🎨 button : color panel opens
* Choose a color
* Click on palette 🎨 button again : nothing happens

**Comment by Tsuricate** [comment]
Hi @alpliar ! 👋 
Thanks a lot for your feedback ! This issue has been corrected, you can now get back to the items panel by clicking again on the color/position button.
Have a nice day ! 🙂
